<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Termos.aspx.cs" Inherits="badDriverWebMockup.Termos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Termos de Uso</h1>
    <p>Olá, bem vindo ao bad driver,O Bad driver é um site que tem como objetivo transpor informações que ajudarão a identificar e mostrar as ocorrencias feitas pelos motoristas no transito,O Bad Driver apresenta os termos de uso, de seu website(www.baddriver.com)</p>
    <p>&nbsp;O uso continuado dos nossos serviços constitui a aceitação de quaisquer alterações ou modificações feitas nos Termos de Uso.</p>
    <h3>1.Aceitação aos Termos de Uso:

&nbsp;</h3>
    <p>1.Ao se cadastrar em nosso site, você concordou, expressa e voluntariamente, com todas as cláusulas destes Termos de Uso. Ao acessar e/ou usar os serviços do Baddriver, você concorda com os Termos de Uso, suas cláusulas e condições, conforme abaixo detalhadas.
</p>
    <p>2.Você está autorizado a utilizar os Serviços do Baddriver somente se você concorda com todas regras e condições estabelecidas nos Termos de Uso.</p>
    <p>3.Se você não concorda com estes Termos de Uso, você não está autorizado a acessar ou utilizar os Dados oferecidos em nosso Site. A utilização dos Serviços Descomplica está expressamente condicionada ao seu consentimento às regras dos Termos de Uso, conforme solicitado quando do seu cadastro em nosso Site.</p>
    <h3>2.Usuários e Membros:</h3>
    <ol style="box-sizing: border-box; margin: 0px 0px 0px 1.25rem; padding: 0px; font-size: 14.8px; line-height: 1.2rem; list-style-position: outside; font-family: Helvetica, Helvetica, Arial, sans-serif; color: rgb(85, 85, 85); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;">
            <ol style="box-sizing: border-box; margin: 0px 0px 0px 1.25rem; padding: 0px; font-size: 12.8px; line-height: 1.2rem; list-style-position: outside; font-family: Helvetica, Helvetica, Arial, sans-serif; color: rgb(85, 85, 85); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Membros:</strong><span>&nbsp;</span>Qualquer pessoa&nbsp; residente em qualquer parte do mundo, pode se tornar Membro do Baddriver. A palavra “Membro” se referirá a qualquer pessoa que tenha se registrado em nossa Pagina.</li>
                <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Usuários:</strong><span>&nbsp;</span>O uso das áreas públicas do Baddriver está disponível para qualquer pessoa, sem necessidade de registro. Para poder usufruir dos serviços privados, reservados aos Membros, o usuário deve se registrar para se tornar um Membro do Baddriver. A palavra “Usuário” se referirá a qualquer usuário que não tenha se registrado como Membro do Descomplica.</li>
                <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Senha e Segurança:</strong><span>&nbsp;</span>Quando você completar o seu processo de registro, você criará uma senha que habilitará seu acesso à nossa Pagina. Você concorda em manter a confidencialidade da sua senha e é inteiramente responsável por qualquer dano resultante da não manutenção dessa confidencialidade e de todas as atividades que ocorrerem através do uso de sua senha. Você concorda em nos notificar imediatamente de qualquer acesso não autorizado de sua senha ou outra quebra de segurança. Você concorda que o Baddriver não será responsabilizado por qualquer perda ou dano que ocorra a partir do não cumprimento desta cláusula.</li>
            </ol>
        </li>
    </ol>
    <h2>3.Informaçoes publicas e Privadas</h2>
    <ol style="box-sizing: border-box; margin: 0px 0px 0px 1.25rem; padding: 0px; font-size: 12.8px; line-height: 1.2rem; list-style-position: outside; font-family: Helvetica, Helvetica, Arial, sans-serif; color: rgb(85, 85, 85); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">“Suas Informações”:</strong><span>&nbsp;</span>são definidas como qualquer informação postada por você ou que você nos dê (direta ou indiretamente), inclusive através do seu processo de registro ou do seu uso de nossa Plataforma, comentários em blogs, mensagens enviadas dentro de nossa Pagina, ou e-mail. Você é o único responsável por Suas Informações, e nós agimos como um canal passivo para a distribuição e publicação de suas Informações Públicas (como definidas abaixo). Não temos qualquer responsabilidade relacionada ao conteúdo das postagens dos usuários em nossa Pagina, decorrente de leis de propriedade intelectual, trabalhistas, privacidade ou outras. Não podemos nos comprometer ao controle de toda e qualquer postagem dos usuários.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">“Informações Públicas”:</strong><span>&nbsp;</span>seu nome, afiliação a companhias e localidade, bem como qualquer parte de Suas Informações que, através do uso de nossa Pagina ou de outra maneira, você envie ou disponibilize para a inclusão em áreas públicas de nossa Pagina.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">“Informação Privada”:</strong><span>&nbsp;</span>qualquer outra parte de Suas Informações que não sejam Informações Públicas será referida como Informação Privada.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">“Áreas públicas”:</strong><span>&nbsp;</span>são aquelas áreas de nossa Plataforma que são acessíveis para alguns ou todos os nossos Membros (p.ex., não restritas à sua visualização apenas) ou para o público geral.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Acessibilidade das Informações Públicas.</strong><span>&nbsp;</span>As suas Informações Públicas podem ser acessíveis e publicadas por programas de publicação automática e por ferramentas de busca, ferramentas de metabusca, crawlers, metacrawlers e outros similares.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Restrições.</strong><span>&nbsp;</span>Ao considerar o uso de nossa Plataforma, você concorda que as Suas Informações:<ol class="inciso" style="box-sizing: border-box; margin: 0px 0px 0px 1.25rem; padding: 0px; font-size: 0.8rem; line-height: 1.2rem; list-style-position: outside; font-family: inherit;">
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">A.não devem ser fraudulentas;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">B.não devem infringir nenhum direito autoral de terceiros, patente, marca registrada, direito de distribuição ou outro direito de propriedade intelectual, de publicação ou privacidade;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">C.não devem violar nenhuma lei, estatuto, ordenação ou regulamento;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">D.não devem ser difamatórias, caluniosas, ameaçadoras ou abusivas;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">E.não devem ser obscenas ou conter pornografia, pornografia infantil, ou fotos de pessoas despidas;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">F.não devem conter vírus, cavalos de tróia, worms, time bombs, cancelbots, easter eggs ou outras rotinas de programação que possam danificar, interferir, interceptar ou desapropriar qualquer sistema, dado ou informação pessoal;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">G.não devem nos responsabilizar ou fazer com que percamos (total ou parcialmente) o serviço do nosso Provedor de Internet ou outros fornecedores;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">H.não devem criar links direta ou indiretamente a qualquer material que você não tenha direito de incluir ou linkar.</li>
            </ol>
        </li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Obrigações:</strong><span>&nbsp;</span>Você concorda também que deverá nos informar um endereço válido de e-mail, tanto na hora de seu registro conosco quanto a cada vez que o seu e-mail mudar. Você concorda também que o seu perfil de Membro, a Newsletter do Baddriver, postagens de comentários em blogs, uploads de fotos ou quaisquer porções da Pagina reservadas apenas a uso dos Membros não devem ser usadas por você para atividades comerciais, vendas de bens e serviços, ou a promoção de uma companhia, bem ou serviço não relacionado ao tópico ou espírito do Baddriver ou de Grupo de Membros em particular. Você será exclusivamente responsável pelas informações que você postar nas áreas publicamente acessíveis da Plataforma, independente de sua intenção ou não de fazê-lo.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Privacidade:</strong><span>&nbsp;</span>Todas as informações pessoais relacionadas ao uso dos Serviços ou ao uso da Plataforma Descomplica estão sujeitas à nossa Política de Privacidade.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Licença.</strong><span>&nbsp;</span>Nós não clamamos propriedade de Suas Informações. Nós usaremos as suas Informações Pessoais Identificáveis apenas de acordo com a nossa Política de Privacidade.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Restrições no Nosso Uso de Suas Informações.</strong><span>&nbsp;</span>Exceto se especificado contrariamente em nossa Política de Privacidade, nós não venderemos, alugaremos ou divulgaremos nenhuma parte de suas Informações Pessoais Identificáveis (como definidas em nossa Política de Privacidade) sobre você (incluindo seu endereço de e-mail) para terceiros.</li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;"><strong style="box-sizing: border-box; font-weight: 700; line-height: inherit;">Consentimento de Divulgação.</strong><span>&nbsp;</span>Você entende e concorda que o Baddriver pode divulgar Suas Informações se requerida a fazê-lo por lei ou por acreditar de boa fé que essa divulgação é razoável e necessária para:<ol class="inciso" style="box-sizing: border-box; margin: 0px 0px 0px 1.25rem; padding: 0px; font-size: 0.8rem; line-height: 1.2rem; list-style-position: outside; font-family: inherit;">
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">A.cooperar com um procedimento judicial, uma ordem judicial ou processo legal sobre nós ou nossa Plataforma;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">B.reforçar os Termos de Uso;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">C.replicar a respeito da infração do direito de terceiros por Suas Informações;</li>
            <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: lower-latin;">D.proteger os direitos, propriedades ou a segurança pessoal do Baddriver, seus empregados, usuários e público.</li>
            </ol>
        </li>
        <li style="box-sizing: border-box; margin: 0.5em 0px; padding: 0px; list-style-type: decimal;">O Baddriver reserva-se o direito, a seu exclusivo critério, de suspender ou terminar o seu uso de nossa Plataforma e de nossos Serviços, de recusar todo e qualquer uso corrente ou futuro de todas ou algumas partes de nossa Plataforma e/ou Serviços.</li>
    </ol>
    


    <p>
        &nbsp;</p>
    


</asp:Content>
