//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace badDriverService.Baddriver.APIv1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="APIv1Soap", Namespace="http://tempuri.org/")]
    public partial class APIv1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListWorstDriversOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListDriversCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListAllDriversOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListLastDriversOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListPlacesWithMoreIncidentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public APIv1() {
            this.Url = global::badDriverService.Properties.Settings.Default.badDriverService_Baddriver_APIv1_APIv1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListWorstDriversCompletedEventHandler ListWorstDriversCompleted;
        
        /// <remarks/>
        public event ListDriversCountCompletedEventHandler ListDriversCountCompleted;
        
        /// <remarks/>
        public event ListAllDriversCompletedEventHandler ListAllDriversCompleted;
        
        /// <remarks/>
        public event ListLastDriversCompletedEventHandler ListLastDriversCompleted;
        
        /// <remarks/>
        public event ListPlacesWithMoreIncidentsCompletedEventHandler ListPlacesWithMoreIncidentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListWorstDrivers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Driver[] ListWorstDrivers() {
            object[] results = this.Invoke("ListWorstDrivers", new object[0]);
            return ((Driver[])(results[0]));
        }
        
        /// <remarks/>
        public void ListWorstDriversAsync() {
            this.ListWorstDriversAsync(null);
        }
        
        /// <remarks/>
        public void ListWorstDriversAsync(object userState) {
            if ((this.ListWorstDriversOperationCompleted == null)) {
                this.ListWorstDriversOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListWorstDriversOperationCompleted);
            }
            this.InvokeAsync("ListWorstDrivers", new object[0], this.ListWorstDriversOperationCompleted, userState);
        }
        
        private void OnListWorstDriversOperationCompleted(object arg) {
            if ((this.ListWorstDriversCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListWorstDriversCompleted(this, new ListWorstDriversCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListDriversCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ListDriversCount() {
            object[] results = this.Invoke("ListDriversCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ListDriversCountAsync() {
            this.ListDriversCountAsync(null);
        }
        
        /// <remarks/>
        public void ListDriversCountAsync(object userState) {
            if ((this.ListDriversCountOperationCompleted == null)) {
                this.ListDriversCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListDriversCountOperationCompleted);
            }
            this.InvokeAsync("ListDriversCount", new object[0], this.ListDriversCountOperationCompleted, userState);
        }
        
        private void OnListDriversCountOperationCompleted(object arg) {
            if ((this.ListDriversCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListDriversCountCompleted(this, new ListDriversCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListAllDrivers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Driver[] ListAllDrivers() {
            object[] results = this.Invoke("ListAllDrivers", new object[0]);
            return ((Driver[])(results[0]));
        }
        
        /// <remarks/>
        public void ListAllDriversAsync() {
            this.ListAllDriversAsync(null);
        }
        
        /// <remarks/>
        public void ListAllDriversAsync(object userState) {
            if ((this.ListAllDriversOperationCompleted == null)) {
                this.ListAllDriversOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListAllDriversOperationCompleted);
            }
            this.InvokeAsync("ListAllDrivers", new object[0], this.ListAllDriversOperationCompleted, userState);
        }
        
        private void OnListAllDriversOperationCompleted(object arg) {
            if ((this.ListAllDriversCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListAllDriversCompleted(this, new ListAllDriversCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListLastDrivers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Driver[] ListLastDrivers() {
            object[] results = this.Invoke("ListLastDrivers", new object[0]);
            return ((Driver[])(results[0]));
        }
        
        /// <remarks/>
        public void ListLastDriversAsync() {
            this.ListLastDriversAsync(null);
        }
        
        /// <remarks/>
        public void ListLastDriversAsync(object userState) {
            if ((this.ListLastDriversOperationCompleted == null)) {
                this.ListLastDriversOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListLastDriversOperationCompleted);
            }
            this.InvokeAsync("ListLastDrivers", new object[0], this.ListLastDriversOperationCompleted, userState);
        }
        
        private void OnListLastDriversOperationCompleted(object arg) {
            if ((this.ListLastDriversCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListLastDriversCompleted(this, new ListLastDriversCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListPlacesWithMoreIncidents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePairOfStringString[] ListPlacesWithMoreIncidents() {
            object[] results = this.Invoke("ListPlacesWithMoreIncidents", new object[0]);
            return ((KeyValuePairOfStringString[])(results[0]));
        }
        
        /// <remarks/>
        public void ListPlacesWithMoreIncidentsAsync() {
            this.ListPlacesWithMoreIncidentsAsync(null);
        }
        
        /// <remarks/>
        public void ListPlacesWithMoreIncidentsAsync(object userState) {
            if ((this.ListPlacesWithMoreIncidentsOperationCompleted == null)) {
                this.ListPlacesWithMoreIncidentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListPlacesWithMoreIncidentsOperationCompleted);
            }
            this.InvokeAsync("ListPlacesWithMoreIncidents", new object[0], this.ListPlacesWithMoreIncidentsOperationCompleted, userState);
        }
        
        private void OnListPlacesWithMoreIncidentsOperationCompleted(object arg) {
            if ((this.ListPlacesWithMoreIncidentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListPlacesWithMoreIncidentsCompleted(this, new ListPlacesWithMoreIncidentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Driver {
        
        private int idField;
        
        private string labelField;
        
        private string modelField;
        
        private string supplierField;
        
        private string colorField;
        
        private int incidentQuantityField;
        
        private Incident[] incidentsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public int IncidentQuantity {
            get {
                return this.incidentQuantityField;
            }
            set {
                this.incidentQuantityField = value;
            }
        }
        
        /// <remarks/>
        public Incident[] Incidents {
            get {
                return this.incidentsField;
            }
            set {
                this.incidentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Incident {
        
        private string latitudeField;
        
        private string longitudeField;
        
        private Photo[] photosField;
        
        private int idField;
        
        private int userIdField;
        
        private int driverIdField;
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public Photo[] Photos {
            get {
                return this.photosField;
            }
            set {
                this.photosField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public int DriverId {
            get {
                return this.driverIdField;
            }
            set {
                this.driverIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Photo {
        
        private int idField;
        
        private string nameField;
        
        private string urlField;
        
        private int incidentIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public int IncidentId {
            get {
                return this.incidentIdField;
            }
            set {
                this.incidentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValuePairOfStringString {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListWorstDriversCompletedEventHandler(object sender, ListWorstDriversCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListWorstDriversCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListWorstDriversCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Driver[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Driver[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListDriversCountCompletedEventHandler(object sender, ListDriversCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListDriversCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListDriversCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListAllDriversCompletedEventHandler(object sender, ListAllDriversCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListAllDriversCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListAllDriversCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Driver[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Driver[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListLastDriversCompletedEventHandler(object sender, ListLastDriversCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListLastDriversCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListLastDriversCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Driver[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Driver[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListPlacesWithMoreIncidentsCompletedEventHandler(object sender, ListPlacesWithMoreIncidentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListPlacesWithMoreIncidentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListPlacesWithMoreIncidentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePairOfStringString[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePairOfStringString[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591